### PR TITLE
Remove Makefile in favor of npm scripts. See hapijs/contrib#14

### PR DESCRIPTION
**Pull request by mtharrison**

### CODE REVIEW

**Comment by hueniverse** [comment]
Might as well fix licenses while in there as well as remove the root index.js file.

**Comment by mtharrison** [comment]
Was it just the year that needed fixing?

**Comment by hueniverse** [comment]
I meant the package.json `licenses` key.

**Comment by mtharrison** [comment]
Woops, sorted now. I'd like to be the maintainer too if this is still up for grabs?

**Comment by hueniverse** [comment]
@mtharrison start by documenting it...

**Pull request merged**
